# Generated by Django 5.0.4 on 2024-04-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_category_login_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('productid', models.IntegerField()),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
