# Generated by Django 5.0.4 on 2024-04-20 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productid',
            new_name='p_id',
        ),
    ]
