# Generated by Django 5.0.4 on 2024-04-20 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_rename_productid_product_p_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productname',
            new_name='Productname',
        ),
    ]
