# Generated by Django 5.0.4 on 2024-04-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_rename_productname_product_productname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='imagename',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
