# Generated by Django 5.0.4 on 2024-04-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_categorycloth_sizecategory_remove_category_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desciption',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
